language: android
android:
  components:
    - platform-tools
    - build-tools-19.1.0
jdk:
  - oraclejdk7
  # - openjdk7

script:
    - echo $ANDROID_HOME
    - find $ANDROID_HOME -name zipalign
    # sdk/build-tools/21.0.1/
    # - cd jenkins
    # - bash ./jenkins_test.sh
    # - cd ..

deploy:
  on:
    all_branches: true

