# language: android
# android:
#   components:
#     - build-tools-19.1.0
#     - android-19

before_deploy:
  - git clone -b test https://github.com/giltsl/travis-test.git
  - cd travis-test
  - gem build dpl.gemspec
  # - rvm 2.1 do ruby -S gem install dpl-*.gem
  - ruby -S gem install dpl-*.gem
  - cd ..
  - /home/travis/build/giltsl/Ham/travis-test/bin/dpl --provider=testfairy
  # - dpl --provider=testfairy

# before_deploy:
#   git clone -b test https://github.com/giltsl/travis-test.git
#   cd travis-test && gem build && gem build dpl.gemspec
#   rvm 2.1 do ruby -S gem install dpl-*.gem
#   cd ..

deploy:
  provider: testfairy

  on:
    all_branches: true
