language: android
jdk:
- openjdk6
script:
- which true
- echo hello
- git clone -b testfairy https://github.com/giltsl/dpl.git
- cd dpl
- git log -n 1
- gem build dpl.gemspec
- gem install dpl-*.gem
- cp *.gem ..
- cd ..
- gem install multipart-post
- sudo echo "" > /home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem
deploy:
  local: true
  provider: testfairy
  platform: android
  api-key:
    secure: WVDGCW0w52czDAUfoc5afPdlnNDSZe4l9itGx+8oSdCfAWq7DEe0v+TcxBGb2RsrHELgR1Gz9fH4C5QzRpL99dY9qzVRLsc+jpEA2vN/nlvVxROg+P4l1uO6l1JZjCNRSpleR+AbTZM1K19fZLvaauySalxbAG0MIggzYDW7PNk=
  app-file: out/ham.apk
  keystore-file: app/debug.keystore
  storepass: android
  alias: androiddebugkey
  on:
    all_branches: true
