# language: ruby
# rvm:
    # - 2.1
    # - 2.2

language: android
# android:
#   components:
#     - build-tools-19.1.0
#     - android-19


script:
  - echo hello
#   - gem build dpl.gemspec
  - ruby -S gem install dpl-*.gem
#   - bundle install

# script:
#   - echo hello
#   - git clone -b test https://github.com/giltsl/travis-test.git
#   - cd travis-test
#   - git log -n 1
# #   - bundle install
#   - gem build dpl.gemspec
# #   - ruby -S gem install dpl-*.gem
#   - rvm 2.2 do ruby -S gem install dpl-*.gem
#   - cp Gemfile .. 
#   - cp dpl.gemspec ..
#   - cp *.gem ..
#   - cd ..

#   - echo $ANDROID_HOME
#   - cd $ANDROID_HOME
#   - find . -name zipalign
#   - echo $JAVA_HOME
#   - cd $JAVA_HOME
#   - find . -name jarsigner


# before_deploy:

#   git clone -b test https://github.com/giltsl/travis-test.git
#   cd travis-test && gem build && gem build dpl.gemspec
#   rvm 2.1 do ruby -S gem install dpl-*.gem
#   cd ..

deploy:
  provider: testfairy
  local: true
  platform: "android"
  api-key: "5f8d490c554f63cf7784174bcdcb3c87f2447709"
  apk: "out/ham.apk"
  proguard-file: "proguard file name"
  keystore-file: "app/debug.keystore"
  storepass: "android"
  alias: "androiddebugkey"
  on:
    all_branches: true
