# language: android
# android:
#   components:
#     - build-tools-19.1.0
#     - android-19

script:
  - echo hello
  - git clone -b testfairy https://github.com/giltsl/travis-test.git
  - cd travis-test
  - git log -n 1
#   - bundle install
  - gem build dpl.gemspec
  - gem install --local dpl-*.gem
  - cp *.gem ..
  - cd ..
#   - which dpl


# script:
#   - echo hello
#   - git clone -b test https://github.com/giltsl/travis-test.git
#   - cd travis-test
#   - git log -n 1
# #   - bundle install
#   - gem build dpl.gemspec
#   - ruby -S gem install dpl-*.gem
# #   - rvm 2.2 do ruby -S gem install dpl-*.gem
#   - cp Gemfile .. 
#   - cp dpl.gemspec ..
#   - cp *.gem ..
#   - cd ..

#   - echo $ANDROID_HOME
#   - cd $ANDROID_HOME
#   - find . -name zipalign
#   - echo $JAVA_HOME
#   - cd $JAVA_HOME
#   - find . -name jarsigner


before_deploy:
#    bundle install
#   - which dpl
#   git clone -b test https://github.com/giltsl/travis-test.git
#   cd travis-test && gem build && gem build dpl.gemspec
#   rvm 2.1 do ruby -S gem install dpl-*.gem
#   cd ..

deploy:
  local: true
  edge: true
  provider: testfairy
  platform: "android"
  api-key: "5f8d490c554f63cf7784174bcdcb3c87f2447709"
  apk: "out/ham.apk"
  proguard-file: "proguard file name"
  keystore-file: "app/debug.keystore"
  storepass: "android"
  alias: "androiddebugkey"
  on:
    all_branches: true
