# language: android
# jdk:
# - openjdk6
# script:
# - which true
# - echo hello
# - git clone https://github.com/testfairy/dpl.git
# - cd dpl
# - git log -n 1
# - gem build dpl.gemspec
# - gem install dpl-*.gem
# - cp *.gem ..
# - cd ..
# - gem install multipart-post
# - sudo echo "" > /home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem

# before_deploy:
#   - echo before_deploy
#   - cd out
#   - ls -lt
#   - cd ..
  

deploy:
  # local: true
  # skip-cleanup: true
  provider: testfairy
  # app-file: out/Empty.ipa
  app-file: out/ham.apk
  keystore-file: out/debug.keystore
  storepass: android
  alias: androiddebugkey
  metrics: "cpu,memory,logcat"
  on:
    all_branches: true
  api-key: "5f8d490c554f63cf7784174bcdcb3c87f2447709"
