language: android
jdk:
- openjdk6
script:
- which true
- echo hello
- git clone -b testfairy https://github.com/giltsl/dpl.git
- cd dpl
- git log -n 1
- gem build dpl.gemspec
- gem install dpl-*.gem
- cp *.gem ..
- cd ..
- gem install multipart-post
- sudo echo "" > /home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem
deploy:
  local: true

  platform: android
  app-file: out/ham.apk
  keystore-file: debug.keystore.enc
  storepass: android
  alias: androiddebugkey
  on:
    all_branches: true
  api-key:
    secure: E13tgHozY4t+c0gyp6/tcRtWCG99gsGrWGcvc/+clzAPEAfaPrbA5raaH+JORrO+FWMIamrqas+eqs0EJrKrpoYS+5scqDcQ4ItFAJWgdIqs5WkeFCo22AT1k2q1zgmNOtNWVBxxIgiPnbIs6Bj+idIyEPAoegsoRxCP7FdyFjw=
before_install:
- openssl aes-256-cbc -K $encrypted_2a19ebee9a0c_key -iv $encrypted_2a19ebee9a0c_iv
  -in debug.keystore.enc -out out/debug.keystore -d
